sudo: true
language: ruby
rvm:
  - "2.0.0"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -"
  - "sudo sh -c 'echo \"deb http://dl.google.com/linux/chrome/deb/ stable main\" >> /etc/apt/sources.list.d/google.list'"
  - "sudo apt-get update"
  - "sudo apt-get install google-chrome-stable"
script:
  - bundle exec cucumber -f progress -r features features